language: node_js

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y nasm

node_js:
  - "8.11.3"

before_script:
  - npm install coveralls

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js